import dynamic from "next/dynamic";

import { MenuProvider } from '../../context/MenuContext';
import "../../styles/globals.scss";


const DynamicMenu = dynamic(() => import('../../components/Menu'));

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <MenuProvider><body><DynamicMenu />{children}</body></MenuProvider>
    </html>
  )
}